apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure Items
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
    ignore:
      - group: ""
        kind: Secret
        jqPathExpressions:
          - '.metadata.annotations["reflector.v1.k8s.emberstack.com/reflects"] != null'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hass
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Home Assistant Components
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
    ignore:
      - group: ""
        kind: Secret
        jqPathExpressions:
          - '.metadata.annotations["reflector.v1.k8s.emberstack.com/reflects"] != null'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: common
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Shared Stuff
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
    ignore:
      - group: ""
        kind: Secret
        jqPathExpressions:
          - '.metadata.annotations["reflector.v1.k8s.emberstack.com/reflects"] != null'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ai
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: AI Experimentation
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
    ignore:
      - group: ""
        kind: Secret
        jqPathExpressions:
          - '.metadata.annotations["reflector.v1.k8s.emberstack.com/reflects"] != null' 