apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  scopes: '[permissionNames]'
  policy.default: role:readonly
  policy.csv: |
    g, admin, role:admin
    g, editor, role:editor
    g, viewer, role:readonly