apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-local
  namespace: ai
  labels:
    app: ollama
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: ai
    app.kubernetes.io/name: ollama
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Gi