apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-local
  namespace: ai
  labels:
    app: ollama
    app.kubernetes.io/component: ollama
    app.kubernetes.io/part-of: ai
    app.kubernetes.io/name: ollama
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui
  namespace: ai
  labels:
    app: openwebui
    app.kubernetes.io/component: openwebui
    app.kubernetes.io/part-of: ai
    app.kubernetes.io/name: openwebui
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-config
  namespace: ai
  labels:
    app: searxng
    app.kubernetes.io/component: searxng
    app.kubernetes.io/part-of: ai
    app.kubernetes.io/name: searxng
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 100Mi
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: sd-webui-data
#  namespace: ai
#  labels:
#    app: sd-webui
#    app.kubernetes.io/component: sd-webui
#    app.kubernetes.io/part-of: ai
#    app.kubernetes.io/name: sd-webui
#  annotations:
#    argocd.argoproj.io/sync-options: Delete=false
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: nfs
#  resources:
#    requests:
#      storage: 50Gi