apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: ai
  labels:
    app: searxng
    app.kubernetes.io/component: searxng
    app.kubernetes.io/name: searxng
    app.kubernetes.io/part-of: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
      app.kubernetes.io/component: searxng
      app.kubernetes.io/name: searxng
      app.kubernetes.io/part-of: ai
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: searxng
        app.kubernetes.io/component: searxng
        app.kubernetes.io/name: searxng
        app.kubernetes.io/part-of: ai
    spec:
      containers:
      - name: searxng
        image: searxng/searxng:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            protocol: TCP
            containerPort: 8080
        env:
          - name: INSTANCE_NAME
            value: "searxng"
          - name: SEARXNG_PORT
            value: "8080"
          - name: SEARXNG_BIND_ADDRESS
            value: "0.0.0.0"
          #- name: SEARXNG_DISABLED_ENGINES
          #  value: "ahmia,torch"
          #- name: SEARXNG_SETTINGS_PATH
          #  value: /etc/searxng/settings.yml
          - name: SEARXNG_LIMITER
            value: /etc/searxng/limiter.toml
          #- name: SEARXNG_ENABLE_BOT_DETECTION
          #- name: SEARXNG_TRUSTED_PROXIES
          #  value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,10.42.0.0/16,10.42.1.0/24"
          - name: SEARXNG_SECRET #SEARXNG_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: searxng-secret
                key: SEARXNG_SECRET_KEY
        volumeMounts:
          - name: searxng-config-pvc
            mountPath: /etc/searxng
          - name: searxng-cache
            mountPath: /var/cache/searxng
        #  - name: etc
        #    mountPath: /etc/searxng
        #  - name: searxng-pvc
        #    mountPath: /var/cache/searxng
        #  - name: settings
        #    mountPath: /etc/searxng/settings.yml
        #    subPath: settings.yml
        #    readOnly: false
        #  - name: settings
        #    mountPath: /etc/searxng/limiter.toml
        #    subPath: limiter.toml
        #    readOnly: false
        securityContext: {}
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      volumes:
        - name: searxng-cache
          emptyDir: {}
        #- name: settings
        #  configMap:
        #    name: searxng-settings
        - name: searxng-config-pvc
          persistentVolumeClaim:
            claimName: searxng-config
        - name: localtime
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: searxng
    app.kubernetes.io/component: searxng
    app.kubernetes.io/name: searxng
    app.kubernetes.io/part-of: ai
  name: searxng
  namespace: ai
spec:
  selector:
    app: searxng
    app.kubernetes.io/component: searxng
    app.kubernetes.io/name: searxng
    app.kubernetes.io/part-of: ai
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  type: ClusterIP
