apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
  namespace: hass
  labels:
    app: piper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: piper
    spec:
      containers:
      - name: piper
        image: rhasspy/wyoming-piper:1.6.3
        imagePullPolicy: IfNotPresent
        args: ["$(voice)","$(voice_name)"]
        ports:
          - protocol: TCP
            containerPort: 10200
        env:
          - name: voice
            value: "--voice"
          - name: voice_name
            value: "en_GB-northern_english_male-medium"
        volumeMounts:
          - name: piper-pvc
            mountPath: /data
            subPath: data
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
        #livenessProbe:
        #  failureThreshold: 3
        #  periodSeconds: 10
        #  successThreshold: 1
        #  tcpSocket:
        #    port: 10400
        #  timeoutSeconds: 1
        securityContext: {}
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      # Ugly to enable the following but it will make it easier to 
      #hostNetwork: true
      #dnsPolicy: ClusterFirstWithHostNet
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.30.1
          - 192.168.0.1
          - 192.168.20.1
        searches:
          - $DOMAIN_NAME
      volumes:
        - name: piper-pvc
          persistentVolumeClaim:
            claimName: piper
        - name: localtime
          hostPath:
            path: /etc/localtime
