apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: planka
  namespace: default
  labels:
    app: planka
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
