apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs
  namespace: external-storage
  labels:
    location: nas
spec:
  chart: nfs-subdir-external-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  targetNamespace: external-storage
  set:
    nfs.server: nas.$DOMAIN_NAME
    nfs.path: /nfs
    storageClass.name: nfs
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs-slow
  namespace: external-storage
  labels:
    location: nas
spec:
  chart: nfs-subdir-external-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  targetNamespace: external-storage
  set:
    nfs.server: nas.$DOMAIN_NAME
    nfs.path: /data1/nfs/volume
    storageClass.name: nfs-slow
  valuesContent: |-
    nodeSelector:
      node-role.kubernetes.io/master: "true"