apiVersion: v1
kind: ConfigMap
metadata:
  name: zwavejs
  namespace: hass
  labels:
    app: zwavejs
data:
  config: |-
    [server]
    hosts = 0.0.0.0:5232
    [encoding]
    [auth]
    [rights]
    [storage]
    filesystem_folder = /data/collections
    [web]
    [logging]
    [headers]
