apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwavejs
  namespace: hass
  labels:
    app: zwavejs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
