apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zwavejs
  namespace: hass
spec:
  encryptedData:
    password: AgBvthUTE80W1rkUy7yJ4FwugO3oV+olAJJv8uoRuq7n2bnZAobrF56m1snleWOrDLJvL4WCbL52IGX5Aur7JPH+pNl4g9MZ7wIWZp2AzwBV4QUM5ncHcRffyvIO1Nt+Iwu7m+/pHax6Cw9ZTJtJ66Q2zzrt3oKEY32fVmsE0evalN+oQXYEtqsa5fXVbkGxGvJc3S7EqMYFFmMzd2a4yVLgDhLCjNNy0cL29IsAtwd47ToDSBymutmkTmeLBumDUr4DU/nNGVwjrDS5YygRcoYsIcjv1gTRd9hQc22vnXk6vWG1rfkhdDbQE8aZSoRz+TBmgvPu8t67Uf5lGRGr36hNrBSViyYl4YGSF80wT06ubV9Ps89BjivrTrlqq9gELArVmXDzQ+cJAFlxZnOgZcFjHLgtZfvO0q7y3z0A0hvt4/Wb5WdhCcPOvYpcFJKt7YfBFL2AjFit5Ly9ZWVdPdWd5kdhESNkEycGNU4UXE/Amua1jsNrZGNiWscjJAjF58Sa+zFM37fGK61XIQImJwz28fDcfjp5BzK6nuceojkEy45teaZYi88syWRIRxMmKYKg2mkxVgVqZEwwh04MjorrejCQ2sabLiTeHolgEo4orAVFcg31gOk3kPUa2NhMpURv4O0Dv156V3qJOJ7xPJXWrSO/5Ec9eiZlOM/cMYb+jEecoPp15SRA8LgfxSQoFvA55YBmrj3U2g==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zwavejs
      name: zwavejs
      namespace: hass
    type: Opaque
status: {}
