apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: zwavejs
  name: zwavejs
  namespace: hass
spec:
  ports:
    - port: 8091 
      targetPort: 8091 
      name: web
    - port: 3000 
      targetPort: 3000 
      name: websocket
  selector:
    app.kubernetes.io/name: zwavejs
  type: ClusterIP
