apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: common
spec:
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:17.4
        env:
          - name: POSTGRES_USER
            value: "thisshouldberandommaybe"
          - name: POSTGRES_PASSWORD
            value: "thisaswellandverylongandcomplicated"
          - name: POSTGRES_DB
            value: "postgres"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresql-volume
          mountPath: /var/lib/postgresql/data
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      volumes:
      - name: postgresql-volume
        persistentVolumeClaim:
          claimName: postgresql
