apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: common
  labels:
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 50Gi
