apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass
  namespace: hass
  labels:
    app: hass
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-media
  namespace: hass
  labels:
    app: hass
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 20Gi
