apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki
  namespace: monitoring
  labels:
    app.kubernetes.io/component: aggregator
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/name: loki
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 50Gi

