apiVersion: v1
kind: Service
metadata:
  name: vector-udp
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: vector
  ports:
    - name: udp-logs
      port: 5140
      targetPort: 5140
      protocol: UDP
