apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-csi
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cert-manager-csi-driver
      repoURL: https://charts.jetstack.io
      targetRevision: v0.8.*   # example – you can bump later
      helm:
        releaseName: cert-manager-csi
        values: |
          syncSecret:
            enabled: true
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              memory: 128Mi
    - path: cert-manager-csi
      repoURL: https://github.com/h00lig4n/k3s.git
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
