apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: container-registry
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  project: common
  source:
    path: container-registry
    repoURL: https://github.com/h00lig4n/k3s.git
    targetRevision: HEAD
