apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: generic-device-plugin
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  project: infrastructure
  source:
    path: generic-device-plugin
    repoURL: https://github.com/h00lig4n/k3s.git
    targetRevision: HEAD
