apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: hass
    server: https://kubernetes.default.svc
  project: common
  sources:
   - path: grafana
     repoURL: https://github.com/h00lig4n/k3s.git
     targetRevision: HEAD
   - path: grafana
     repoURL: https://github.com/h00lig4n/k3s-private.git
     targetRevision: HEAD
