apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
spec:
  destination:
    namespace: hass
    server: https://kubernetes.default.svc
  project: hass
  sources:
    - path: influxdb
      repoURL: https://github.com/h00lig4n/k3s.git
      targetRevision: HEAD
    - path: influxdb
      repoURL: https://github.com/h00lig4n/k3s-private.git
      targetRevision: HEAD
