apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  project: common
  sources:
    - repoURL: https://github.com/h00lig4n/k3s-private.git
      targetRevision: HEAD
      path: kube-vip/overlays/prod
  kustomize:
    resources:
      - $base