apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwakeword
spec:
  destination:
    namespace: hass
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openwakeword
    repoURL: https://github.com/h00lig4n/k3s.git
    targetRevision: HEAD
