apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: piper
  namespace: argocd
spec:
  destination:
    namespace: hass
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  project: hass
  source:
    path: piper
    repoURL: https://github.com/h00lig4n/k3s.git
    targetRevision: HEAD
