apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: planka
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
  - path: planka
    repoURL: https://github.com/h00lig4n/k3s.git
    targetRevision: HEAD
  - path: planka
    repoURL: https://github.com/h00lig4n/k3s-private.git
    targetRevision: HEAD
  - chart: planka
    repoURL: http://plankanban.github.io/planka
    targetRevision: 0.2.20
    helm:
      values: |
        admin_email: "demo@demo.demo" #Limitation of Planka. Create new admin
        admin_password: "demo"
        admin_name: "Demo Demo"
        admin_username: "demo"
        existingSecretkeySecret: planka
        # existingAdminCredsSecret: planka
        nodeSelector:
          node-role.kubernetes.io/worker: "true"
        resources:
          limits:
             cpu: 500m
             memory: 500Mi
          requests:
             cpu: 100m
             memory: 128Mi
        postgresql:
          enabled: false
        existingDburlSecret: planka
        persistence:
          enabled: true
          existingClaim: planka
          storageClass: "nfs"
          accessMode: ReadWriteOnce
          size: 10Gi
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: plan.$DOMAIN_NAME
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: tls-certificate
              hosts:
                - plan.$DOMAIN_NAME
            
