apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: common
spec:
  destination:
    namespace: common
    server: https://kubernetes.default.svc
  project: infrastructure
  sources:
  - chart: prometheus-community
    helm:
      parameters:
      - name: installCRDs
        value: "true"
      releaseName: cert-manager
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: v1.17.1
