apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: common
spec:
  destination:
    namespace: common
    server: https://kubernetes.default.svc
  project: infrastructure
  sources:
  - chart: prometheus-stack
    helm:
    repoURL: https://prometheus-community.github.io/helm-charts
    valueFiles:
      - "../prometheus/values.yaml"
