apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pushprox
  namespace: argocd
spec:
  project: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://charts.rancher.io
    targetRevision: 103.0.1
    chart: rancher-pushprox
    helm:
      releaseName: pushprox-kube-proxy
      values: |
        namespaceOverride: monitoring
        metricsPort: 10249
        component: k3s-server
        serviceMonitor:
          enabled: true
        clients:
          port: 10013
          useLocalhost: true
          https:
            enabled: true
            useServiceAccountCredentials: true
            insecureSkipVerify: true
        rbac:
          additionalRules:
          - nonResourceURLs: ["/metrics/cadvisor"]
            verbs: ["get"]
          - apiGroups: [""]
            resources: ["nodes/metrics"]
            verbs: ["get"]
          nodeSelector:
            node-role.kubernetes.io/monitor: "true"
          tolerations:
            - effect: "NoExecute"
              operator: "Exists"
            - effect: "NoSchedule"
              operator: "Exists"
