apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  project: infrastructure
  sources:
    - path: reloader
      repoURL: https://github.com/h00lig4n/k3s.git
      targetRevision: HEAD
