apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webnut
  namespace: argocd
spec:
  destination:
    namespace: common
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  project: infrastructure
  sources:
    - path: webnut
      repoURL: https://github.com/h00lig4n/k3s.git
      targetRevision: kusto
