apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui
  namespace: ai
  labels:
    app: openwebui
    app.kubernetes.io/component: gui
    app.kubernetes.io/part-of: ai
    app.kubernetes.io/name: openwebui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: openwebui
      app.kubernetes.io/component: gui
      app.kubernetes.io/part-of: ai
      app.kubernetes.io/name: openwebui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openwebui
        app.kubernetes.io/component: gui
        app.kubernetes.io/part-of: ai
        app.kubernetes.io/name: openwebui
    spec:
      containers:
      - name: openwebui
        image: ghcr.io/open-webui/open-webui:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        env:
          - name: OLLAMA_BASE_URL
            value: "http://ollama:11434"
          - name: RAG_EMBEDDING_ENGINE
            value: ollama
          - name: EMBEDDING_MODEL
            value: "nomic-embed-text"
          - name: AUDIO_STT_ENGINE
            value: openai
          - name: CONTENT_EXTRACTION_ENGINE
            value: tika
          - name: TIKA_SERVER_URL
            value: http://tika:9998
          - name: ENABLE_WEB_SEARCH
            value: "true"
          - name: WEB_SEARCH_ENGINE
            value: "searxng"
          - name: SEARXNG_QUERY_URL
            value: "http://searxng:8080/search?q=<query>"
          - name: ENABLE_RAG
            value: "true"
          - name: VECTOR_DB
            value: qdrant
          - name: QDRANT_URI
            value: "http://qdrant:6333"
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openai
                key: api-key
          #OIDC
          #- name: ENABLE_LOGIN
          #  value: "false"
          - name: OAUTH_PROVIDER
            value: "oidc"
          - name: OAUTH_PROVIDER_NAME
            value: "Casdoor"  
          - name: OAUTH_CLIENT_ID
            value: "openwebui"
          - name: OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: oidc
                key: client-secret
          - name: OPENID_PROVIDER_URL
            valueFrom:
              secretKeyRef:
                name: oidc
                key: well-known-url
          #- name: OAUTH_AUTHORIZATION_URL
          #  valueFrom:
          #    secretKeyRef:
          #      name: oidc
          #      key: auth-url
          #- name: OAUTH_TOKEN_URL
          #  valueFrom:
          #    secretKeyRef:
          #      name: oidc
          #      key: token-url
          #- name: OAUTH_USERINFO_URL
          #  valueFrom:
          #    secretKeyRef:
          #      name: oidc
          #      key: user-info-url
          - name: OAUTH_REDIRECT_URI
            valueFrom:
              secretKeyRef:
                name: oidc
                key: redirect-url
          - name: OAUTH_SCOPE
            value: "openid profile email"
          - name: OAUTH_USERNAME_CLAIM
            value: "preferred_username"
          - name: OAUTH_EMAIL_CLAIM
            value: "email"
          - name: OAUTH_ROLE_CLAIM
            value: "roles"
          - name: OAUTH_ALLOWED_ROLES
            value: "admin,user"         
          - name: ENABLE_OAUTH_SIGNUP
            value: "true"
          - name: OAUTH_CODE_CHALLENGE_METHOD
            value: "S256"
          - name: ENABLE_OAUTH_ROLE_MANAGEMENT
            value: "true"
        startupProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        tty: true
        volumeMounts:
          - name: openwebui-pvc
            mountPath: /app/backend/data 
        securityContext: {}
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1500Mi"
            cpu: "1500m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      volumes:
        - name: openwebui-pvc
          persistentVolumeClaim:
            claimName: openwebui