apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: openwebui
  namespace: ai
  labels:
    app: openwebui
    app.kubernetes.io/component: gui
    app.kubernetes.io/part-of: ai
    app.kubernetes.io/name: openwebui
spec:
  hosts:
    - ai.mydomain.com
  scaleTargetRef:
    name: openwebui
    kind: deployment
    apiVersion: apps/v1
    service: openwebui
    port: 8080
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 1800   # 30 minutes