preUpgradeChecker:
  jobEnabled: false

global:
  revisionHistoryLimit: 2
  nodeSelector:
    longhorn-storage: "true"

image:
  longhorn:
    manager:
      repository: longhornio/longhorn-manager
      tag: v1.11.0-hotfix-1
    instanceManager:
      repository: longhornio/longhorn-instance-manager
      tag: v1.11.0-hotfix-1

defaultSettings:
  defaultReplicaCount: 2
  defaultDataPath: /mnt/usb/longhorn
  createDefaultDiskLabeledNodes: true
  disableSchedulingOnCordonedNode: true
  replicaSoftAntiAffinity: true
  storageMinimalAvailablePercentage: 15

  # Pi-specific timeout tuning
  iscsiTimeout: 60
  replicaReplenishmentWaitInterval: 600
  concurrentReplicaRebuildPerNodeLimit: 1
  concurrentVolumeBackupRestorePerNodeLimit: 1

longhornManager:
  nodeSelector:
    longhorn-storage: "true"

longhornDriver:
  nodeSelector:
    longhorn-storage: "true"

longhornUI:
  nodeSelector:
    longhorn-storage: "true"

ingress:
  enabled: true
  ingressClassName: traefik
  host: longhorn.example.com
  tls: true
  tlsSecret: tls-certificate
