apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: qdrant
  namespace: ai
  labels:
    app: qdrant
    app.kubernetes.io/component: vector
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/part-of: ai
spec:
  scaleTargetRef:
    name: qdrant
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 60
  triggers:
    - type: kubernetes-workload
      metadata:
        podSelector: app=openwebui
        value: "1"