apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant
  namespace: ai
  labels:
    app: qdrant
    app.kubernetes.io/component: vector
    app.kubernetes.io/part-of: ai
    app.kubernetes.io/name: qdrant
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi