apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate
  namespace: default
spec:
  dnsNames:
    - "*.mydomain.com"
  commonName: "*.mydomain.com"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: tls-certificate
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default, dev, ai, hass, kube-system, common, argocd, monitoring, auth"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default, dev, ai, hass, kube-system, common, argocd, monitoring, auth" # Control auto-reflection namespaces
