apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 60s
      evaluation_interval: 60s
      body_size_limit: 15MB
      sample_limit: 1500
      target_limit: 30
      label_limit: 30
      label_name_length_limit: 200
      label_value_length_limit: 200
      query_log_file: query.log
      scrape_failure_log_file: fail.log
    
      external_labels:
        monitor: prometheus
  
 
    scrape_configs:
  # The job name is added as a label `job=` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 60s

    static_configs:
      - targets: ['localhost:9090']

