apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: common
data:
  prometheus.yml: |
    global:
      scrape_interval: 60s
      evaluation_interval: 60s
      body_size_limit: 15MB
      sample_limit: 1500
      target_limit: 30
      label_limit: 30
      label_name_length_limit: 200
      label_value_length_limit: 200
      query_log_file: query.log
      scrape_failure_log_file: fail.log
    
      external_labels:
        monitor: prometheus
  
    #rule_files:
      #  - "first.rules"
      #  - "my/*.rules"
  
  
    scrape_configs:
      - job_name: k8s

            refresh_interval: 10m
          - files:
              - bar/*.yaml
  
        static_configs:
          - targets: ["localhost:9090", "localhost:9191"]
            labels:
              my: label
              your: label
    
      #relabel_configs:

  
  
  
  
  alerting:
    alertmanagers:
      - scheme: https
        static_configs:
          - targets:
              - "1.2.3.4:9093"
              - "1.2.3.5:9093"
              - "1.2.3.6:9093"
  
  storage:
    tsdb:
      out_of_order_time_window: 30m
  
  tracing:
    endpoint: "localhost:4317"
    client_type: "grpc"
    headers:
      foo: "bar"
    timeout: 5s
    compression: "gzip"
    tls_config:
      cert_file: valid_cert_file
      key_file: valid_key_file
      insecure_skip_verify: true
