apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: common
data:
  prometheus.yml: |
    global:
      scrape_interval: 60s
      evaluation_interval: 60s
      body_size_limit: 15MB
      sample_limit: 1500
      target_limit: 30
      label_limit: 30
      label_name_length_limit: 200
      label_value_length_limit: 200
      query_log_file: query.log
      scrape_failure_log_file: fail.log
    
      external_labels:
        monitor: prometheus
  
    #rule_files:
      #  - "first.rules"
      #  - "my/*.rules"
  
  
    scrape_configs:
      - job_name: k8s

            refresh_interval: 10m
          - files:
              - bar/*.yaml
  
        static_configs:
          - targets: ["localhost:9090", "localhost:9191"]
            labels:
              my: label
              your: label

