apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  namespace: common
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: external-storage
  hostPath:
    path: 
