apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  namespace: common
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 50Gi
