apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uisp
  namespace: default
  labels:
    app: uisp
    app.kubernetes.io/component: uisp
    app.kubernetes.io/part-of: ubiquiti
    app.kubernetes.io/name: ubiquiti
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
