apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: unifi
  namespace: default
  labels:
    app.kubernetes.io/component: unifi
    app.kubernetes.io/part-of: ubiquiti
    app.kubernetes.io/name: ubiquiti
spec:
  entryPoints:
    - stun
  routes:
  - services:
    - name: unifi
      port: 3478
