apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: unifi
    app.kubernetes.io/part-of: ubiquiti
    app.kubernetes.io/name: ubiquiti
    app.kubernetes.io/instance: svc-clusterip
  name: unifi
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: default-skipverify@kubernetescrd
spec:
  ports:
    - port: 8443
      targetPort: 8443
      name: https
  selector:
    app.kubernetes.io/component: unifi
    app.kubernetes.io/part-of: ubiquiti
    app.kubernetes.io/name: ubiquiti
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: unifi2
    app.kubernetes.io/part-of: ubiquiti
    app.kubernetes.io/name: ubiquiti
    app.kubernetes.io/instance: svc-loadbalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.30.51
  name: unifi2
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 80
      targetPort: 80
      name: portal
    - port: 8843
      targetPort: 8843
      name: portal-https
    - port: 3478
      targetPort: 3478
      protocol: UDP
      name: stun
    - port: 6789
      targetPort: 6789
      name: speed
    - port: 10001
      targetPort: 10001
      protocol: UDP
      name: discovery
  selector:
    app.kubernetes.io/component: unifi
    app.kubernetes.io/part-of: ubiquiti
    app.kubernetes.io/name: ubiquiti
  type: LoadBalancer
