apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt
  namespace: hass
  labels:
    app: mqtt
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 2Gi
