apiVersion: v1
kind: Secret
metadata:
  labels:
    app: mqtt
  name: mqtt
  namespace: hass
type: Opaque
stringData:
  healthcheck.sh: | 
    #!/bin/sh 
    mosquitto_sub -u <<myuser>> -P <<mypassword>> -t '$SYS/#' -C 1 -i healthcheck -W 3
