apiVersion: v1
kind: Service
metadata:
  labels:
    service: mqtt-svc
    app: mqtt
  name: mqtt-svc
spec:
  ports:
  - name:  tls
    port: 8883
    targetPort:  8883
    protocol:  TCP
  selector:
    app: mqtt
  type: LoadBalancer
