apiVersion: v1
kind: ConfigMap
metadata:
  name: container-registry
  namespace: default
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
      tag:
        concurrencylimit: 8
      delete:
        enabled: true
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
        Access-Control-Allow-Origin: ['*']
        Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
        Access-Control-Allow-Headers: ['Accept']
        Access-Control-Expose-Headers: ['Docker-Content-Digest']
    auth:
      htpasswd:
        realm: basic-realm
        path: /etc/registry
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
