apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-docker-registry
  labels:
    app: ui-docker-registry
    namespace: default
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  replicas: 1
  selector:
    matchLabels:
      app: ui-docker-registry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ui-docker-registry
    spec:
      containers:
        - image: joxit/docker-registry-ui:main
          imagePullPolicy: Always
          name: ui-docker-registry
          ports:
            - containerPort: 80
          env:
            - name: SINGLE_REGISTRY
              value: "true"
            - name: REGISTRY_TITLE
              value: Thomason Container Registry
            - name: DELETE_IMAGES
              value: "true"          
            - name: SHOW_CONTENT_DIGEST
              value: "true"
            - name: SHOW_CATALOG_NB_TAGS
              value: "true"
            - name: NGINX_PROXY_PASS_URL
              value: https://docker.{{mydomain}}
            - name: CATALOG_MIN_BRANCHES
              value: "1"
            - name: CATALOG_MAX_BRANCHES
              value: "1"            
            - name: TAGLIST_PAGE_SIZE
              value: "100"
            - name: REGISTRY_SECURED
              value: "false"
            - name: CATALOG_ELEMENTS_LIMIT
              value: "1000"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/worker
        operator: Equal
        value: true 
