apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: default
spec:
  routes:
    - match: Host(`traefik.$DOMAIN_NAME`) && PathPrefix(`/api`) || PathPrefix(`/dashboard`)
      kind: Rule
      middlewares:
        - name: auth
          namespace: default 
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    secretName: tls-certificate
