apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: locked
spec:
  chain:
    middlewares:
    - name: redirect-https
    - name: auth-users
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: default
spec:
  basicAuth:
    headerField: X-WebAuth-User
    secret: authsecret
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: dashboard-auth
  namespace: default
spec:
  basicAuth:
    headerField: X-WebAuth-User
    secret: authsecret
---
apiVersion: traefik.io/v1alpha1
kind: MiddlewareTCP
metadata:
  name: address-whitelist
  namespace: default
spec:
  ipAllowList:
    sourceRange:
      - 192.168.0.9
      - 192.168.0.10
      - 192.168.0.16
