apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: hass
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
