apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: hass
spec:
  encryptedData:
    password: AgAJN60QZBWpfOTCNEFj0zE+FYy79ymDW5t3t1n4MWz8AnvlJt9qvt2J+IJz7ttUPAccP4Jusyy+kNSI/tTtT77k27PTWtEmAdHMfJTZ1XCJ/THQJVqvz27DoR88r17bCt8M0XMZ1WEL4HSdIUWWMRmAsVv1SQJT4AmAFBNZ9kqnpY02SkeeaMxzIMs1bTdS2S42D2U998TfZ/iElvrjc0u9I4EettF6/LoM/wI3mBXZtQTCP1OO0JxnW7dmYziWgltxJOpgGArBPszeo0mQn4QjVHfJcCly4GRzpekpaoe18p3JLHqoaZ3ydq4Gc2yXfUy4Pin8FDjiJjyW+SIwikub2p2avDscgn3pBze4IJcfrfb53Xuitp+XHrrbtd/9HDpX9LYZ6aEnIcvjPYFROt7z0j4pb+4747w1abyG5SMjfaeXb60qjz1Od1O69zWmkCcXFGADkiJuvQ5HdbUFP4Xi+dF7dpoUHmDYsW7vXqX95cpoB6BipOGYxFXAngaIIwQmeOd46VuMTvVTvzR/3HQb3KI/BnhHoqDUQa8gEYS620nuNuRY8ImhHfHO/cqqLIAvDE2s0ij3l1mORmPlL5sdHgIvR3gFM/HuOkzb+06+dSRtReQDNMLNVK24mTh4EUdbojtgAuEtQFPlg6KcVQHuSwzjec0daoZ/pXiWnbGKXo95qPVoeZXcl3pf2HjxoXv8unjvq+A8mw==
    username: AgBNXMPQYVApWcD/xdK1iQ/FW0X+Cfv39G4PXuu6oL6fU1a3IdjF9TrKrKt+8pP/bcEaRUt2SYeU/CKC8+e0uCSApTnq7fNpHbozI8Fx9+jn23esowWA/1Julxp+gz2q9o+NaIdhnaUre9qSbc8aqO4FetGnzTHeSvvTf1tFCfHrvwnJPAzx11uzi1JGg4O0zhqunoXh8rPw64xtYZvv9E39M1kBoDtG6alabeacEbHFqHBaTO87GNCNF8zog2yLjz03MfOrHMvCh8chKcoopXRMyp/ouy7hfn1gII7pnqG0z4W27pNPFK7beUFohCh7BxqgeyfvWWYJ9ndgZcBvQJZcqnw10oPfQPtVtBSsNMnDXzWFmoIkw0Ip5bF3UvwwcZulNq5O1y5IbGESoZSFpTzhafmJtvksYJlXoZJPdZeZ4BUfB1pCFaRGBKdM2/QLLKByPlBvTzx9BYbxqdGISaDs/bPl5i7s1k6Y4FRO6BgGmyhUSsBWJdtD1E8g8cyknybwKMIADKjuCJH2XjjdMyTEDBJe1CW2LYnjpZr616WS21y4ErGCL5F16ZJbB4/UoUUhmtN9rH/W8lN+EwWWrnqnVo2EltKLc13P+JpG32SnwMx1Z8P4CpZCSxjHJFcgCFiLIPbU3erTAE8QmvYcrfw0aVSnVq8ntCcN6zvPO4HWYZWra9N4Psbmx2OWS2YszyDAXW/5
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana
      name: grafana
      namespace: hass
    type: Opaque
status: {}

