apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-config
  namespace: ai
  labels:
    app: searxng
    app.kubernetes.io/component: searxng
    app.kubernetes.io/part-of: ai
    app.kubernetes.io/name: searxng
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 100Mi