apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  #labels:
  #  image-policy: semver
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  project: infrastructure
  sources:
    - repoURL: https://github.com/h00lig4n/k3s-private.git
      targetRevision: HEAD
      path: uptime-kuma/overlays/prod