      containers:
      - command:
        - /var/run/argocd/argocd-cmp-server
        env:
        - name: DOMAIN_NAME
          value: replace-with-domain-name
        image: your-registry/envsubst-cmp-plugin:latest
        imagePullPolicy: Always
        name: envsubst
        resources: {}
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: cmp-tmp
      volumes:
      - emptyDir: {}
        name: cmp-tmp
