# This is a not very secret secret
apiVersion: v1
kind: Secret
metadata:
  name: k3s
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/h00lig4n/k3s.git
