apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwakeword
  namespace: hass
  labels:
    app: openwakeword
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwakeword
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openwakeword
    spec:
      containers:
      - name: openwakeword
        image: rhasspy/wyoming-openwakeword:1.10.0
        imagePullPolicy: IfNotPresent
        args: ["$(preload)", "$(model)", "$(modeldir)","$(dir)"]
        ports:
          - name: udp
            protocol: TCP
            containerPort: 10400
        env:
          - name: preload
            value: "--preload-model"
          - name: model
            value: "ok_nabu"
          - name: modeldir
            value: "--custom-model-dir"
          - name: dir
            value: "/custom"
        volumeMounts:
          - name: openwakeword-pvc
            mountPath: /data
            subPath: data
          - name: openwakeword-pvc
            mountPath: /custom
            subPath: custom
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 10400
          timeoutSeconds: 1
        securityContext: {}
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      # Ugly to enable the following but it will make it easier to 
      #hostNetwork: true
      #dnsPolicy: ClusterFirstWithHostNet
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.0.1
        searches:
          - $DOMAIN_NAME
      volumes:
        - name: openwakeword-pvc
          persistentVolumeClaim:
            claimName: openwakeword
        - name: localtime
          hostPath:
            path: /etc/localtime
