apiVersion: v1
kind: Service
metadata:
  labels:
    app: openwakeword
  name: openwakeword
  namespace: hass
spec:
  ports:
    - name: openwakeword
      port: 10400
      targetPort: udp
      protocol: TCP
  selector:
    app: openwakeword
  type: ClusterIP
