apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama
  namespace: ai
  labels:
    app: ollama
    app.kubernetes.io/component: ollama
    app.kubernetes.io/part-of: ai
    app.kubernetes.io/name: ollama
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui
  namespace: ai
  labels:
    app: openwebui
    app.kubernetes.io/component: openwebui
    app.kubernetes.io/part-of: ai
    app.kubernetes.io/name: openwebui
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng
  namespace: ai
  labels:
    app: searxng
    app.kubernetes.io/component: searxng
    app.kubernetes.io/part-of: ai
    app.kubernetes.io/name: searxng 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
