apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama
  namespace: ai
  labels:
    app: ollama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui
  namespace: ai
  labels:
    app: openwebui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng
  namespace: ai
  labels:
    app: searxng
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
