  apiVersion: argoproj.io/v1alpha1
  kind: ConfigManagementPlugin
  metadata:
    name: envsubst
  spec:
    init:
      command: [sh]
      args: [-c, "echo 'Initializing envsubst plugin...'" ]
    generate:
      command: [sh, -c]
      args:
        - |
          find . -type f -name '*.yaml' -exec sh -c 'echo "---"; envsubst < "$1"' _ {} \;
    discover:
      fileName: "./*.yaml"
