apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: common
  labels:
    app: postgresql
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-local-pvc
  namespace: common
  labels:
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
  annotations:
    argocd.argoproj.io/sync-options: Delete=false