apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: esphome-updater
  namespace: argocd
spec:
  namespace: argocd
  commonUpdateSettings:
    updateStrategy: "semver"
  writeBackConfig:
    method: "git:secret:argocd/image-updater-git-creds"
    gitConfig:
      repository: "https://github.com/h00lig4n/k3s-private.git"
      branch: "main:version-updates"
      writeBackTarget: "kustomization"
  applicationRefs:
    - namePattern: "*"
      labelSelectors:
        matchLabels:
          image-policy: semver
      images:
        - alias: "docker"
          imageName: "registry:2.x.x"
        - alias: "dockerui"
          imageName: "joxit/docker-registry-ui:2.x.x"
        - alias: "grafana"
          imageName: "grafana/grafana-oss:12.3.x"
        - alias: "esphome"
          imageName: "esphome/esphome:2026.1.x"
        - alias: "hass"
          imageName: "homeassistant/home-assistant:2026.1.x"
        - alias: "openwakeword" 
          imageName: "rhasspy/wyoming-openwakeword:2.x.x"
        - alias: "wyomingPiper" 
          imageName: "rhasspy/wyoming-piper:2.x.x"
# Will use labels for this one.