apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: esphome-updater
  namespace: argocd
spec:
  namespace: argocd
  writeBackConfig:
    method: git
    gitConfig:
      repository: "https://github.com/h00lig4n/k3s-private.git"
      branch: "main:version-updates"
      writeBackTarget: "kustomization"
  applicationRefs:
    - namePattern: "esphome"
      labelSelectors:
        matchLabels:
          environment: "production"
      images:
        - alias: "esphome"
          imageName: "esphome/esphome:2026.1.x"
          commonUpdateSettings:
            updateStrategy: "semver"
        - alias: "hass"
          imageName: "homeassistant/home-assistant:2026.2.x"
          commonUpdateSettings:
            updateStrategy: "semver"
# Will use labels for this one.