apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.200-192.168.0.255
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool-vlan30
  namespace: metallb-system
spec:
  addresses:
  - 192.168.30.50-192.168.30.99
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - ip-pool
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: vlan30-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - ip-pool-vlan30
