admin_email: "example@mydomain.com"
admin_name: "Admin"
existingSecretkeySecret: planka
existingAdminCredsSecret: planka
nodeSelector:
  node-role.kubernetes.io/worker: "true"
resources:
  limits:
      cpu: 600m
      memory: 500Mi
  requests:
      cpu: 280m
      memory: 250Mi
oidc:
  enabled: true
  issuerUrl: https://mydomain.com
  clientId: planka_client_id
  clientSecret: planka_client_secret
  scopes: openid profile email
  admin:
    rolesAttribute: roles
    roles: admin
extraEnv:
  - name: "OIDC_USE_OAUTH_CALLBACK"
    value: "false"
#  - name: "OIDC_RESPONSE_MODE"
#    value: "query"
#  - name: "OIDC_CLAIMS_SOURCE"
#    calue: "id_token"
  - name: "NODE_ENV"
    value: "development"
  - name: "OIDC_DEBUG"
    value: "false"
  - name: "DEBUG"
    value: "*"
  - name: "SHOW_DETAILED_AUTH_ERRORS"
    value: "true"
postgresql:
  enabled: false
existingDburlSecret: planka
persistence:
  enabled: true
  existingClaim: planka
  storageClass: "nfs"
  accessMode: ReadWriteOnce
  size: 10Gi
ingress:
  enabled: true
  className: traefik
  hosts:
    - host: mydomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-certificate
      hosts:
        - mydomain.com