admin_email: "example@mydomain.com"
admin_name: "Admin"
existingSecretkeySecret: planka
existingAdminCredsSecret: planka
nodeSelector:
  node-role.kubernetes.io/worker: "true"
resources:
  limits:
      cpu: 500m
      memory: 500Mi
  requests:
      cpu: 160m
      memory: 250Mi
oidc:
  enabled: true
  issuerUrl: https://mydomain.com
  clientId: planka_client_id
  clientSecret: planka_client_secret
  scopes: openid profile email
  admin:
    rolesAttribute: roles
    roles: admin
extraEnv:
  - name: "OIDC_ENFORCED"
    value: "true"
postgresql:
  enabled: false
existingDburlSecret: planka
persistence:
  enabled: true
  existingClaim: planka
  storageClass: "nfs"
  accessMode: ReadWriteOnce
  size: 10Gi
ingress:
  enabled: true
  className: traefik
  hosts:
    - host: mydomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-certificate
      hosts:
        - mydomain.com