apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: portainer
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: unifi
  namespace: portainer
subsets:
  - addresses:
      - hostname: portainer.$DOMAIN_NAME
    ports:
      - name: https
        port: 8443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi
  namespace: portainer
spec:
  ingressClassName: traefik
  rules:
    - host: unifi.$DOMAIN_NAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unifi
                port:
                  number: 8443
  tls:
    - secretName: unifi-tls
      hosts:
        - unifi.$DOMAIN_NAME
