apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai
  namespace: argocd
spec:
  destination:
    namespace: ai
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  project: ai
  sources:
    - path: AI
      repoURL: https://github.com/h00lig4n/k3s.git
      targetRevision: HEAD
    - path: AI
      repoURL: https://github.com/h00lig4n/k3s-private.git
      targetRevision: HEAD
