apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai
  namespace: argocd
spec:
  destination:
    namespace: ai
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  project: ai
  sources:
    - chart: nvidia-device-plugin
      repoURL: https://nvidia.github.io/k8s-device-plugin
      targetRevision: 0.18.2
      helm:
        values: |
          nodeSelector:
            node-role.kubernetes.io/ai: "true"
          tolerations:
            - key: nvidia.com/gpu
              operator: Exists
              effect: NoSchedule
    - repoURL: https://github.com/h00lig4n/k3s-private.git
      targetRevision: HEAD
      path: ai/overlays/prod