apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  project: infrastructure
  sources:
    - chart: cert-manager
      helm:
        parameters:
        - name: installCRDs
          value: "true"
        releaseName: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.18.0
    - repoURL: https://github.com/h00lig4n/k3s-private.git
      path: cert-manager/overlays/prod
      targetRevision: main
  kustomize:
    resources:
      - $base
