apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
  #labels:
  #  image-policy: semver
spec:
  destination:
    namespace: auth
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  project: common
  sources:
    - chart: dex
      repoURL: https://charts.dexidp.io
      targetRevision: 0.24.0
      helm:
        valueFiles:
#          - $values/dex/helm/values.yaml
          - $values-private/dex/helm/values.yaml
#    - repoURL: https://github.com/h00lig4n/k3s.git
#      targetRevision: HEAD
#      ref: values
    - repoURL: https://github.com/h00lig4n/k3s-private.git
      targetRevision: HEAD
      ref: values-private
    - repoURL: https://github.com/h00lig4n/k3s-private.git
      targetRevision: HEAD
      path: dex/overlays/prod