apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
  #labels:
  #  image-policy: semver
spec:
  destination:
    namespace: auth
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  project: common
  sources:
    - path: dex/overlays/prod
      repoURL: https://github.com/h00lig4n/k3s-private.git
      targetRevision: HEAD