apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
spec:
  project: ai
  sources:
    - chart: nvidia-device-plugin
      repoURL: https://nvidia.github.io/k8s-device-plugin
      targetRevision: 0.14.5
      helm:
        values: |
          nodeSelector:
            node-role.kubernetes.io/ai: "true"
         
          # Allow running on the GPU-tainted node
          tolerations:
            - key: nvidia.com/gpu
              operator: Exists
              effect: NoSchedule
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true