apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
spec:
  project: ai
  sources:
    - chart: nvidia-device-plugin
      repoURL: https://nvidia.github.io/k8s-device-plugin
      targetRevision: 0.18.2
      helm:
        values: |
          devicePlugin:
            enabled: true
          gfd:
            enabled: false
          nfd:
            enabled: false
          affinity: {}
          nodeSelector:
            node-role.kubernetes.io/ai: "true"
          # Allow running on the GPU-tainted node
          tolerations:
            - key: nvidia.com/gpu
              operator: Exists
              effect: NoSchedule
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true