apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  labels:
    image-policy: semver
spec:
  destination:
    namespace: common
    server: https://kubernetes.default.svc
  project: common
  syncPolicy:
    automated:
      selfHeal: true
  sources:
    - repoURL: https://github.com/h00lig4n/k3s-private.git
      targetRevision: HEAD
      path: postgresql/overlays/prod