apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true 
      - ServerSideApply=true
  project: infrastructure
  sources:
    - chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 25.0.0
      helm:
        releaseName: prometheus
        values: |
          alertmanager:
            enabled: false

          prometheus-pushgateway:
            enabled: false

          prometheus-node-exporter:
            enabled: true

          kube-state-metrics:
            enabled: true
            collectors:
              - pods
              - deployments
              - nodes

          server:
            # global:
            #  scrape_interval: 60s  
            extraArgs:
              query.max-concurrency: 5
            resources:
              requests:
                cpu: 100m
                memory: 384Mi
              limits:
                memory: 2Gi
            persistentVolume:
              enabled: false

            service:
              type: ClusterIP

            retention: "2d"

            nodeSelector:
              node-role.kubernetes.io/control-plane: "true"

            tolerations:
              - key: "node-role.kubernetes.io/control-plane"
                operator: "Exists"
                effect: "NoSchedule"

          serverFiles:
            prometheus.yml:
              global:
                scrape_interval: 60s

              scrape_configs:
                - job_name: prometheus
                  static_configs:
                    - targets: ['localhost:9090']

                - job_name: traefik
                  static_configs:
                    - targets:
                        - traefik.kube-system.svc.cluster.local:9100

                - job_name: kube-state-metrics
                  static_configs:
                    - targets:
                        - kube-state-metrics.monitoring.svc.cluster.local:8080

                - job_name: node-exporter
                  kubernetes_sd_configs:
                    - role: pod
                  relabel_configs:
                    - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                      regex: prometheus-node-exporter
                      action: keep

                - job_name: kubelet
                  scheme: https
                  tls_config:
                    insecure_skip_verify: true
                  kubernetes_sd_configs:
                    - role: node


  #        extraScrapeConfigs: |
  #          - job_name: 'traefik'
  #            static_configs:
  #              - targets:
  #                  - traefik.kube-system.svc.cluster.local:9100