apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt
  namespace: argocd
  labels:
    image-policy: semver
spec:
  destination:
    namespace: hass
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  project: hass
  sources:
    - repoURL: https://github.com/h00lig4n/k3s-private.git
      targetRevision: HEAD
      path: zigbee2mqtt/overlays/prod