apiVersion: apps/v1
kind: Deployment
metadata:
  name: casdoor
  namespace: common
  labels:
    app: casdoor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casdoor
  template:
    metadata:
      labels:
        app: casdoor
    spec:
      containers:
        - name: casdoor
          image: casbin/casdoor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DRIVER
              value: "postgres"
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: casdoor
                  key: dataSourceName
            - name: RUNNING_IN_DOCKER
              value: "true"
          volumeMounts:
            - mountPath: /init_data.json
              name: casdoor-conf
              subPath: init_data.json
            - mountPath: /conf/app.conf
              name: casdoor-conf
              subPath: app.conf
          env:       
            - name: RUNNING_IN_DOCKER
              value: "true"
      volumes:
        - configMap:
            name: casdoor
          name: casdoor-conf
