apiVersion: apps/v1
kind: Deployment
metadata:
  name: casdoor
  namespace: common
  labels:
    app: casdoor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casdoor
  template:
    metadata:
      labels:
        app: casdoor
    spec:
      containers:
        - name: casdoor
          image: casbin/casdoor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: RUNNING_IN_DOCKER
              value: "true"
            - name: httpport 
              value: "8000"  
            - name: runmode  
              value: "prod"  
              
            - name: driverName
              value: postgres
            - name: dbName
              value: casdoor
            - name: dataSourceName
              valueFrom:
                secretKeyRef:
                  name: casdoor
                  key: dataSourceName
          volumeMounts:
            - mountPath: /init_data.json
              name: casdoor-init-data-volume
              subPath: init_data.json
         #   - mountPath: /conf
         #     name: conf
          env:       
            - name: RUNNING_IN_DOCKER
              value: "true"
      volumes:
        - configMap:
            name: casdoor
          name: casdoor-init-data-volume
        - name: conf
          hostPath:
            path: /conf
