apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  namespace: auth
  labels:
    app: dex
    app.kubernetes.io/component: dex
    app.kubernetes.io/name: dex
    app.kubernetes.io/part-of: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
        app.kubernetes.io/component: dex
        app.kubernetes.io/name: dex
        app.kubernetes.io/part-of: auth
    spec:
      containers:
        - name: dex
          image: dexidp/dex/dex:v2.45.0-distroless
          args: ["serve", "/etc/dex/config.yaml"]
          ports:
            - containerPort: 5556
          env:
            - name: LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lldap-secrets
                  key: LLDAP_LDAP_USER_PASS
          volumeMounts:
            - name: config
              mountPath: /etc/dex
          resources:
            requests:
              cpu: 50m
              memory: 80Mi
            limits:
              cpu: 300m
              memory: 160Mi
      volumes:
        - name: config
          configMap:
            name: dex-config