apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: container-registry
  namespace: default
  labels:
    app: container-registry
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 50Gi
