apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome
  namespace: hass
  labels:
    app: esphome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esphome
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: esphome
    spec:
      containers:
      - name: esphome
        image: esphome/esphome:2024.8.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 6052
        env:
          - name: "ESPHOME_DASHBOARD_USE_PING"
            value: "true"
          - name: TZ
            value: Europe/Stockholm
          - name: "USERNAME"
            valueFrom:
              secretKeyRef:
                name: esphome
                key: username
          - name: "PASSWORD"
            valueFrom:
              secretKeyRef:
                name: esphome
                key: password
        volumeMounts:
          - name: esphome-pvc
            mountPath: /config
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
        securityContext:
          privileged: true
        nodeSelector:
          node-role.kubernetes.io/worker: "true"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      # The following is ugly so not used. Can replace dnsPolicy and dnsConfig if you want to discovery on LAN.
      #hostNetwork: true
      #dnsPolicy: ClusterFirstWithHostNet
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - {{MY-DNS-SERVER}}
        searches:
          - {{MYDOMAIN}}
      volumes:
        - name: esphome-pvc
          persistentVolumeClaim:
            claimName: esphome
        - name: localtime
          hostPath:
            path: /etc/localtime
