apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: esphome
  namespace: hass
  labels:
    app.kubernetes.io/name: esphome
  annotations:
    #cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Home Automation Hub
    gethomepage.dev/group: Home Automation
    gethomepage.dev/name: ESP Home
    gethomepage.dev/widget.type: esphome
    gethomepage.dev/widget.url: https://esp.$DOMAIN_NAME
spec:
  ingressClassName: traefik
  rules:
    - host: esp.$DOMAIN_NAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: esphome
                port:
                  number: 6052
  tls:
    - secretName: tls-certificate
      hosts:
        - esp.$DOMAIN_NAME
