apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: esphome
  namespace: hass
  annotations:
    #cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: esp.$DOMAIN_NAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: esphome
                port:
                  number: 6052
  tls:
    - secretName: tls-certificate
      hosts:
        - esp.$DOMAIN_NAME
