apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome
  namespace: hass
  labels:
    app: esphome
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
