apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: esphome
  namespace: hass
spec:
  encryptedData:
    password: AgClGmXCTccYu7aQGf8Eu5kL+SITH3xVRH6r4zrqnyjXg/zhzmJzDcutUypcCvqMRLInw8p3Tft3vRPrN8VQLWcmBBzURDtH++cM5Igo/KPj2G3cCiqoAoKmjUuQTK6NVzq0V12D5PZd950GcWEDAsbGxhgXR/i2qOtME3+GyTjrd6tHkhzUiXbFX5KKxbHJKeqgfaDuFBaDzLD3pkxbJkTjThH4VRy2MqW98QeU1NrXORghEqLWm3YLmnfvVrNfxsArW1fhXPsHkNempy9Z/fR4qlNfzOg4K8K5hqpSEfn5gDZ3jXG71+FeSFoQqPRwUvd3BEuc3ck+cXwizLhP1dC59ieXTf0JqY1kdPoVQglggeWEJltv37SEQb34EgHTcF4YR0kRsmbGYyx92GU25ow66r5NjeAJ9HvE/+gVbYqnUItet9y52ALutq39qQw5GGOoFNvY7iTqJaaBc+CaxOVhLEemYzFqnjP1Lf+gnB8Q61MT5Tkd41M6PynCAIMNJtDncOLjaCf0BX+Ibfu9oMlauq7YA1HlwlqH02iGYOFTPXAM1vgEvOP9lNsrXQAucOmW/80g9hYKjbf4Nmk73NtGS7xvUE7vaLvuTuPGyX1ULrDANjwvV71gXOL0D78XczUOZq55u4/rcNqKvwbjEuwLQs5xQqJWlxUxwxkskeDx/ts/y/EtCKfzk5I+iRjAH4NowzobhH5eNg==
    username: AgCn99Wwvw44yfbMFL3/dMx/1624Jm3YO4C4Csc1bbxODQxCPFQkrmN2f2rvyGI1k+GQNm/ipqxC241JEvHCCgzrDN7XJJP03L5Z5Ds3UlNSq4kvcApvdIqAtQzeFamMP2v3QLJI403P4IXsC+0XXELQElJON4tMweNUaBovJpJRLFkIGs48BJIkcfy0BJAe+PNlz7tgIOJQV53AY3nLSLBqi9CdsFbQtkSrs/l8icND88ZvhZT03NR3ZBzJ5ba/4JKFp5hC4PsdbYpL22jPo1/zXRBMWslDFeohcCkcTJYesWqmi8Kgg1AMZv2T7y+aZvSJ0vFXwW7gb4nGSn5PBtDI3NjTafxu9GrQphfbquzSnhwSNouWPO+n1FA0h90PKoMVdWaXt2rosFPPMbyw0hzD1yplU9ILTIwnBj1uZZ+0U5/bN14bG9mfducZMkh2PH0m1QxLW4ceQTxFJmULUlNTuesI05iiiHq+Xq7s/640v4ow1N0HX2K5C40N5wxrX7Ju4zpKzNIYuU8rhrOdL4fq5f+ad1rjHW83aMRc3WmPnUane+XVT+UfWFRvIZq+dlsATs/dQzjsH4+lhhS+SiNBgjHaY9DMM7saGgutOHg0vV1FvKpi7tSROqYqlE400rTVRt2SQf/4ctbxmSIzmd2Ew3z/G4MyaDbuQ6SpIhMexyLkPEsEKlUU0xrhj8yjLfm6kiLb
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app: esphome
      name: esphome
      namespace: hass
    type: Opaque
status: {}
