apiVersion: v1
kind: Service
metadata:
  labels:
    app: esphome
  name: esphome
  namespace: hass
spec:
  selector:
    app: esphome
  ports:
  - name: esphome
    port: 6052
    targetPort: 6052
  type: ClusterIP
