apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbee2mqtt
  namespace: hass
  labels:
    app.kubernetes.io/name: zigbee2mqtt
  annotations:
    #cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd, default-dashboard-auth@kubernetescrd
        gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Zigbee Controller
    gethomepage.dev/group: Home Automation
    gethomepage.dev/name: Zigbee2MQTT
    gethomepage.dev/icon: si-zigbee2mqtt
    gethomepage.dev/widget.type: greeting
    gethomepage.dev/widget.url: https://zigbee.$DOMAIN_NAME
spec:
  ingressClassName: traefik
  rules:
    - host: zigbee.$DOMAIN_NAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zigbee2mqtt
                port:
                  number: 8080
  tls:
    - secretName: tls-certificate
      hosts:
        - zigbee.$DOMAIN_NAME
