apiVersion: v1
kind: Secret
metadata:
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
  namespace: hass
type: Opaque
stringData:
  username: "{{mqtt-username}}"
  password: "{{mqtt-password}}"
  network_key: "{{mqtt-network-key"
