apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: influxdb
  namespace: hass
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: influxdb.$DOMAIN_NAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: influxdb
                port:
                  number: 8086
  tls:
    - secretName: tls-certificate
      hosts:
        - influxdb.$DOMAIN_NAME
