apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
  namespace: hass
  labels:
    app: influxdb
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 50Gi
