apiVersion: v1
kind: Secret
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: hass
type: Opaque
stringData:
  username: {{influx_username}}
  password: {{influx_password}}
  org: {{influx_init_org}}
  adminToken: {{influx_admin_token}}
