apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certs-pvc
  namespace: common
  annotations:
    argocd.argoproj.io/sync-options: Delete=true
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-slow
  resources:
    requests:
      storage: 1Gi
