apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-writer
  namespace: common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-writer
  template:
    metadata:
      labels:
        app: cert-writer
    spec:
      containers:
      - name: writer
        image: alpine:latest
        command: /run/run.sh
        env:
          - name: EDGE_USER
            valueFrom:
              secretKeyRef:
                name: edge-router
                key: EDGE_USER
          - name: EDGE_HOST
            valueFrom:
              secretKeyRef:
                name: edge-router
                key: EDGE_HOST
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
        volumeMounts:
        - name: pvc
          mountPath: /exports
        - name: cm
          mountPath: /certs
          readOnly: true
        - name: sshkey
          mountPath: /root/.ssh
          readOnly: true
        - name: script
          mountPath: /run
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: certs-pvc
      - name: cm
        secret:
          secretName: tls-certificate
      - name: sshkey
        secret:
          secretName: edge-ssh-key
          defaultMode: 0600
      - name: script
        configMap:
          name: cert-writer-config
          defaultMode: 0755
