apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-writer
  namespace: common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-writer
  template:
    metadata:
      labels:
        app: cert-writer
    spec:
      containers:
      - name: writer
        image: alpine:latest
        command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache openssh coreutils &&
          mkdir -p /exports/tls-certificate &&
          while true; do
            echo "cert-writer loop running..."
            # Always copy cert-manager outputs to NFS
            cp -f /certs/* /exports/tls-certificate/ 2>/dev/null || true
        
            CERT_DIR=/exports/tls-certificate
            PEM=$CERT_DIR/server.pem
            SUMFILE=$CERT_DIR/.server.pem.sha256
        
            if [ -f "$CERT_DIR/tls.crt" ] && [ -f "$CERT_DIR/tls.key" ]; then
              echo "Certificate changed, syncing to EdgeRouter..."
              # Build PEM
              cat "$CERT_DIR/tls.crt" "$CERT_DIR/tls.key" > "$PEM"
              chmod 600 "$PEM"
        
              # Calculate checksum
              NEWSUM=$(sha256sum "$PEM" | awk '{print $1}')
              OLDSUM=""
              [ -f "$SUMFILE" ] && OLDSUM=$(cat "$SUMFILE")
        
              if [ "$NEWSUM" != "$OLDSUM" ]; then
                echo "Certificate changed, syncing to EdgeRouter..."
        
                scp -i /root/.ssh/id_ed25519 -o StrictHostKeyChecking=no "$PEM" "$EDGE_USER@$EDGE_HOST:/config/auth/certificates/server.pem"

                # Restart EdgeRouter GUI AFTER new cert is in place
                ssh -i /root/.ssh/id_ed25519 -o StrictHostKeyChecking=no "$EDGE_USER@$EDGE_HOST" "restart gui"
        
                echo "$NEWSUM" > "$SUMFILE"
              else
                echo "Certificate unchanged."
              fi
            fi
        
            sleep 3600
          done
        env:
          - name: EDGE_USER
            valueFrom:
              secretKeyRef:
                name: edge-router
                key: EDGE_USER
          - name: EDGE_HOST
            valueFrom:
              secretKeyRef:
                name: edge-router
                key: EDGE_HOST
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
        volumeMounts:
        - name: pvc
          mountPath: /exports
        - name: cm
          mountPath: /certs
          readOnly: true
        - name: sshkey
          mountPath: /root/.ssh
          readOnly: true
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: certs-pvc
      - name: cm
        secret:
          secretName: tls-certificate
      - name: sshkey
        secret:
          secretName: edge-ssh-key
          defaultMode: 0600
