apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate-staging
  namespace: default
spec:
  dnsNames:
    - "*.$DOMAIN_NAME"
  commonName: "*.$DOMAIN_NAME"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: tls-staging-certificate
